def get_groups() -> list:
    return [
        ('([a-z]|_)+', 'IDENT', 1),
        ('(-?)[0-9]+', 'NUM_LIT', 2),
        ('`.?`', 'CHAR_LIT', 3),
        ('".*"', 'STR_LIT', 4),
        ('add', 'ADD', 5),
        ('sub', 'SUB', 6),
        ('mult', 'MULT', 7),
        ('div', 'DIV', 8),
        (':=', 'ASGN', 9),
        ('&', 'AND', 10),
        ('\|', 'OR', 11),
        ('\^', 'NOT', 12),
        ('isGreater', 'GT', 13),
        ('isEqual', 'EQ', 14),
        ('\.', 'ENDSTAT', 15),
        (',', 'COMMA', 16),
        ('\(', 'LPAREN', 17),
        ('\)', 'RPAREN', 18),
        ('\[', 'LBRACK', 19),
        ('\]', 'RBRACK', 20),
        ('=>', 'ARROW', 21),
        ('~[^~]*~', 'CMNT', 22),
        ('\s', 'WHTSPC', 23),
        ('func', 'FUNC', 24),
        ('entry', 'MAIN', 25),
        ('var', 'VAR', 26),
        ('fix', 'CONST', 27),
        ('num', 'NUM', 28),
        ('ascii', 'CHAR', 29),
        ('num@', 'NUM_ADDR', 30),
        ('ascii@', 'CHAR_ADDR', 31),
        ('num#', 'NUM_ARR', 32),   # worried about how this guy is treated
        ('ascii#', 'STRING', 33),
        ('give', 'RETURN', 34),
        ('check', 'IF', 35),
        ('other', 'ELSE', 36),
        ('iterif', 'LOOP', 37),
        ('read', 'IN', 38),
        ('write', 'OUT', 39),
        ]

def get_default_code() -> str:
    return 'fix num a := 2.'
